In [21]:
import pandas as pd

In [22]:
df = pd.read_parquet("../data/final/final_all_historical_prices_parquet.parquet")
df.describe(include='all')

,Date,000001.SS,000016.SS,0001.HK,0002.HK,0003.HK,000300.SS,0005.HK,0006.HK,0011.HK,...,^STI,^STOXX,^STOXX50E,^TASI.SR,^TECDAX,^TWII,^VIX,^W5000,^XAU,^XOI
count,2613,2429.000000,1.000000,2464.000000,2464.000000,2464.000000,1128.000000,2464.000000,2464.000000,2464.000000,...,2495.000000,2515.000000,2515.000000,1964.000000,2537.000000,2398.000000,2492.000000,2484.000000,2492.000000,2492.000000
unique,2613,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2025-11-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,3175.988689,3012.968994,49.808930,58.943162,7.921288,4096.020043,47.106803,38.120555,109.137600,...,3211.226725,421.597157,3854.260636,9386.245832,2909.009470,14355.892806,18.484884,37656.212722,115.944121,1389.444075
std,NaN,273.500285,NaN,10.690727,6.136764,1.906249,533.129093,16.896226,5.083720,18.997109,...,360.665248,63.856386,715.027686,2165.665753,622.671789,4757.370937,7.313988,12281.827872,42.269311,380.361538
min,NaN,2464.363037,3012.968994,31.946815,41.535061,4.732096,3159.250000,20.975872,29.475760,69.362846,...,2233.479980,279.660004,2385.820068,5416.470215,1485.010010,7663.974609,9.140000,18656.050781,38.840000,469.679993
25%,NaN,2979.125977,3012.968994,40.604053,55.150864,6.276226,3754.364929,35.741769,35.031153,93.092659,...,3064.960083,373.664993,3347.559937,7380.167603,2572.060059,10495.010254,13.530000,27775.297852,83.747499,1134.699982
50%,NaN,3184.979980,3012.968994,47.551210,59.440666,7.647267,3968.160034,44.574022,36.996239,107.349861,...,3204.820068,403.820007,3605.090088,8823.004883,3028.040039,12917.915039,16.695001,36130.179688,112.215000,1282.525024
75%,NaN,3364.649902,3012.968994,59.854810,63.887542,9.525528,4464.514893,51.597656,39.917656,123.066860,...,3324.540039,464.279999,4276.090088,11456.482910,3339.159912,17322.670410,21.464999,45606.250000,139.525002,1748.740021
max,NaN,4016.331055,3012.968994,72.983292,71.836044,12.450092,5341.680176,110.900002,52.391899,154.369308,...,4472.259766,577.030029,5711.060059,13814.849609,3986.959961,28334.589844,82.690002,68749.273438,329.320007,2260.439941

In [23]:
df = pd.read_csv("../data/final/data_cleaned/constituent_verification_summary.csv")
df.describe(include='all')

                Index Name    Raw Count  Verified Count Success Rate
count                   71    71.000000       71.000000           71
unique                  71          NaN             NaN           22
top     Russell 2000 Index          NaN             NaN            0
freq                     1          NaN             NaN           33
mean                   NaN    84.464789       68.211268          NaN
std                    NaN   267.311740      262.980766          NaN
min                    NaN     0.000000        0.000000          NaN
25%                    NaN     0.000000        0.000000          NaN
50%                    NaN    18.000000        0.000000          NaN
75%                    NaN    50.000000       32.000000          NaN
max                    NaN  1970.000000     1950.000000          NaN

In [24]:
df1 = pd.read_csv("../data/final/final_company_info_usd.csv")
df1.describe(include='all')

,Company Ticker,Sector,Industry,MarketCap,Currency,MarketCap_USD
count,3833,3833,3833,3.833000e+03,3833,3.833000e+03
unique,3833,11,143,NaN,12,NaN
top,ZYME,Financial Services,Banks - Regional,NaN,USD,NaN
freq,1,657,327,NaN,2980,NaN
mean,NaN,NaN,NaN,9.298390e+10,NaN,2.579573e+10
std,NaN,NaN,NaN,6.671614e+11,NaN,1.674892e+11
min,NaN,NaN,NaN,1.464957e+07,NaN,9.527557e+06
25%,NaN,NaN,NaN,8.729140e+08,NaN,8.386097e+08
50%,NaN,NaN,NaN,3.647448e+09,NaN,3.258173e+09
75%,NaN,NaN,NaN,1.537718e+10,NaN,1.209766e+10
max,NaN,NaN,NaN,1.995751e+13,NaN,5.036908e+12

In [25]:
df1 = pd.read_csv("../data/final/data_cleaned/_DJU.csv")
df1.describe(include='all')

                   Company Name Company Ticker
count                        15             15
unique                       15             15
top     American Electric Power            AEP
freq                          1              1

In [26]:
df1 = pd.read_csv("../data/final/data_cleaned/master_indices_list.csv")
df1.describe(include='all')

,Index Name,Ticker,Country,Continent,Latitude,Longitude
count,71,71,71,71,71.000000,71.000000
unique,71,71,32,6,NaN,NaN
top,Dow Jones Global Titans 50 Inde,^DJGT,United States,North America,NaN,NaN
freq,1,1,21,23,NaN,NaN
mean,NaN,NaN,NaN,NaN,31.705265,8.002524
std,NaN,NaN,NaN,NaN,25.143730,78.109529
min,NaN,NaN,NaN,NaN,-41.500083,-99.151468
25%,NaN,NaN,NaN,NaN,25.939156,-74.006015
50%,NaN,NaN,NaN,NaN,40.712728,4.351697
75%,NaN,NaN,NaN,NaN,47.374449,72.869203
max,NaN,NaN,NaN,NaN,59.325117,172.834408

In [27]:
df1 = pd.read_csv("../data/final/master_constituents_list.csv")
df1.describe(include='all')

                 Index Name Company Name Company Ticker
count                  4843         4843           4843
unique                   34         4083           3980
top      Russell 2000 Index          IBM            IBM
freq                   1950            7              7